### ISSUE TITLE
Error while running npm server/bin/automigrate.js

### ISSUE THREAD

**Issue by sgarggit** [strongloop/loopback-example-oracle#2] opened 2015-03-18 09:35 UTC
WARNING: LoopBack connector "oracle" is not installed as any of the following mo
dules:

 ./connectors/oracle
loopback-connector-oracle

To fix, run:

    npm install loopback-connector-oracle

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error:
WARNING: LoopBack connector "oracle" is not installed as any of the following mo
dules:

 ./connectors/oracle
loopback-connector-oracle

To fix, run:

    npm install loopback-connector-oracle

    at DataSource.setup (C:\Users\sgarg\wrkdir\loopback-example-oracle\node_modules\loopback-datasource-juggler\lib\datasource.js:294:28)
    at new DataSource (C:\Users\sgarg\wrkdir\loopback-example-oracle\node_modules\loopback-datasource-juggler\lib\datasource.js:101:8)
    at Object.registry.createDataSource (C:\Users\sgarg\wrkdir\loopback-example-oracle\node_modules\loopback\lib\registry.js:311:12)
    at dataSourcesFromConfig (C:\Users\sgarg\wrkdir\loopback-example-oracle\node_modules\loopback\lib\application.js:391:19)
    at EventEmitter.app.dataSource (C:\Users\sgarg\wrkdir\loopback-example-oracle\node_modules\loopback\lib\application.js:218:12)
    at C:\Users\sgarg\wrkdir\loopback-example-oracle\node_modules\loopback-boot\lib\executor.js:155:9
    at C:\Users\sgarg\wrkdir\loopback-example-oracle\node_modules\loopback-boot\lib\executor.js:224:5
    at Array.forEach (native)
    at forEachKeyedObject (C:\Users\sgarg\wrkdir\loopback-example-oracle\node_modules\loopback-boot\lib\executor.js:223:20)
    at setupDataSources (C:\Users\sgarg\wrkdir\loopback-example-oracle\node_modules\loopback-boot\lib\executor.js:154:3)

Still the same error after setting my NODE_PATH to
 `C:\Users\sgarg;C:\Users\sgarg\wrkdir\loopback-example-oracle\node_modules;C:\Users\sgarg\node_modules`

Also set PATH to point to the instantclient folder.

Please help.

Thanks,
Sachin

**Comment by superkhau** [comment] 2015-03-18 18:10
Did you install the oracle connector via `npm install loopback-connector-oracle`? For future references, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by sgarggit** [comment] 2015-03-19 08:04
yes, I installed oracle connector through  npm install loopback-connector-oracle.

**Comment by sgarggit** [comment] 2015-03-31 09:31
I am still stuck on the same problem. Can anybody help me on this.

**Comment by superkhau** [comment] 2015-03-31 17:27
Can you list the steps you've taken?

```
1. slc loopback
2. slc loopback-connector-oracle
?
```

?

**Comment by superkhau** [comment] 2015-05-12 08:37
@sgarggit Are you still running into issues with this?

**Comment by superkhau** [comment] 2015-05-13 00:08
Closing as duplicate of strongloop/loopback-connector-oracle#39

**Closed by superkhau** 2015-05-13 00:08 UTC
Labels: #wip, triage, waiting
